---
# Example 7: DaemonSet for monitoring (privileged but controlled)
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      hostNetwork: true
      hostPID: false
      hostIPC: false
      
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      
      containers:
      - name: monitor
        # Older Ubuntu with CVEs, but needs some host access for monitoring
        image: ubuntu:20.04
        
        command:
          - /bin/bash
          - -c
          - |
            while true; do
              echo "Monitoring node..."
              sleep 30
            done
        
        securityContext:
          # This DaemonSet needs some privileges but we still limit what we can
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN  # Only add what's strictly necessary
              - SYS_PTRACE
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      volumes:
      - name: tmp
        emptyDir: {}
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      
      volumes:
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
      - name: tmp
        emptyDir: {}
