apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: wordpress
          image: wordpress:6.7.2-php8.2-apache
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 33
            runAsGroup: 33
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: ["ALL"]
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: wp-content
              mountPath: /var/www/html/wp-content
              readOnly: true
            - name: tmp
              mountPath: /tmp
              readOnly: true
      volumes:
        - name: wp-content
          emptyDir: {}
        - name: tmp
          emptyDir: {}
