apiVersion: v1
kind: Pod
metadata:
  name: busybox-debug
  labels:
    app: busybox
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: busybox
      image: busybox:1.37.0
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        privileged: false
        capabilities:
          drop: ["ALL"]
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "10m"
          memory: "8Mi"
  restartPolicy: Never
