apiVersion: v1
kind: Pod
metadata:
  name: example-4-drop-caps
spec:
  containers:
  - name: old-wordpress
    # Vulnerable Image: 'wordpress:5.0' (from 2018) is extremely
    # old and has numerous known, exploitable vulnerabilities.
    image: wordpress:5.0
    securityContext:
      # 1. Don't run as root
      runAsNonRoot: true
      runAsUser: 33  # 'www-data' user in this image
      runAsGroup: 33 # 'www-data' group
      
      # 2. Don't allow privilege escalation
      allowPrivilegeEscalation: false
      
      # 3. Drop all kernel capabilities
      capabilities:
        drop:
        - "ALL"
      
      # 4. Make filesystem read-only
      readOnlyRootFilesystem: true
      
    # WordPress needs a writable volume for uploads, themes, etc.
    volumeMounts:
    - name: wp-content
      mountPath: /var/www/html/wp-content
  volumes:
  - name: wp-content
    emptyDir: {}
