name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # ratchet:actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build vex8s binary
        run: make build

      - name: Upload vex8s binary to release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # ratchet:softprops/action-gh-release@v2
        with:
          files: bin/vex8s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
